/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SketchbookRouteImport } from './routes/sketchbook'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsCitroenUrbanResqoreRouteImport } from './routes/projects.citroen-urban-resqore'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'

const SketchbookRoute = SketchbookRouteImport.update({
  id: '/sketchbook',
  path: '/sketchbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCitroenUrbanResqoreRoute =
  ProjectsCitroenUrbanResqoreRouteImport.update({
    id: '/citroen-urban-resqore',
    path: '/citroen-urban-resqore',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/learn': typeof LearnRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sketchbook': typeof SketchbookRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/citroen-urban-resqore': typeof ProjectsCitroenUrbanResqoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/learn': typeof LearnRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sketchbook': typeof SketchbookRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/citroen-urban-resqore': typeof ProjectsCitroenUrbanResqoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/learn': typeof LearnRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sketchbook': typeof SketchbookRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/citroen-urban-resqore': typeof ProjectsCitroenUrbanResqoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/learn'
    | '/projects'
    | '/sketchbook'
    | '/projects/$slug'
    | '/projects/citroen-urban-resqore'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/learn'
    | '/projects'
    | '/sketchbook'
    | '/projects/$slug'
    | '/projects/citroen-urban-resqore'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/learn'
    | '/projects'
    | '/sketchbook'
    | '/projects/$slug'
    | '/projects/citroen-urban-resqore'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LearnRoute: typeof LearnRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SketchbookRoute: typeof SketchbookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sketchbook': {
      id: '/sketchbook'
      path: '/sketchbook'
      fullPath: '/sketchbook'
      preLoaderRoute: typeof SketchbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/citroen-urban-resqore': {
      id: '/projects/citroen-urban-resqore'
      path: '/citroen-urban-resqore'
      fullPath: '/projects/citroen-urban-resqore'
      preLoaderRoute: typeof ProjectsCitroenUrbanResqoreRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsCitroenUrbanResqoreRoute: typeof ProjectsCitroenUrbanResqoreRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsCitroenUrbanResqoreRoute: ProjectsCitroenUrbanResqoreRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LearnRoute: LearnRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SketchbookRoute: SketchbookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
